// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelHelperDb;

namespace TravelHelperDb.Migrations
{
    [DbContext(typeof(TravelHelperDatabaseContext))]
    [Migration("20210601193225_CreateCustomSchema")]
    partial class CreateCustomSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TravelHelperDb.CategorySet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NaviId")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategorySet");
                });

            modelBuilder.Entity("TravelHelperDb.CitySet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Lng")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CitySet");
                });

            modelBuilder.Entity("TravelHelperDb.Geo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CityEn")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CountryEn")
                        .HasColumnType("text");

                    b.Property<string>("Lat")
                        .HasColumnType("text");

                    b.Property<string>("Lng")
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("RegionEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Geo");
                });

            modelBuilder.Entity("TravelHelperDb.NaviAddressInfoSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ContainerAddress")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("SelfAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.ToTable("NaviAddressInfoSet");
                });

            modelBuilder.Entity("TravelHelperDb.PlacePointSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CustomName")
                        .HasColumnType("text");

                    b.Property<int>("NaviAddressInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NaviAddressInfoId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("PlacePointSet");
                });

            modelBuilder.Entity("TravelHelperDb.ScheduleSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TempPoint")
                        .HasColumnType("integer");

                    b.Property<int>("TravelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TravelId");

                    b.ToTable("ScheduleSet");
                });

            modelBuilder.Entity("TravelHelperDb.TravelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TravelCategoryCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.HasIndex("TravelCategoryCategoryId");

                    b.ToTable("TravelCategory");
                });

            modelBuilder.Entity("TravelHelperDb.TravelSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelSet");
                });

            modelBuilder.Entity("TravelHelperDb.UserSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<int?>("UserSettingsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingsId");

                    b.ToTable("UserSet");
                });

            modelBuilder.Entity("TravelHelperDb.UserSettingsSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("SelectedTravelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserSettingsSet");
                });

            modelBuilder.Entity("TravelHelperDb.CategorySet", b =>
                {
                    b.HasOne("TravelHelperDb.CategorySet", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("TravelHelperDb.NaviAddressInfoSet", b =>
                {
                    b.HasOne("TravelHelperDb.CategorySet", "Category")
                        .WithMany("NaviAddressInfoSet")
                        .HasForeignKey("CategoryId");

                    b.HasOne("TravelHelperDb.CitySet", "City")
                        .WithMany("NaviAddressInfoSet")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("TravelHelperDb.PlacePointSet", b =>
                {
                    b.HasOne("TravelHelperDb.NaviAddressInfoSet", "NaviAddressInfo")
                        .WithMany("PlacePointSet")
                        .HasForeignKey("NaviAddressInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelHelperDb.ScheduleSet", "Schedule")
                        .WithMany("PlacePointSet")
                        .HasForeignKey("ScheduleId");
                });

            modelBuilder.Entity("TravelHelperDb.ScheduleSet", b =>
                {
                    b.HasOne("TravelHelperDb.TravelSet", "Travel")
                        .WithMany("ScheduleSet")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelHelperDb.TravelCategory", b =>
                {
                    b.HasOne("TravelHelperDb.CategorySet", "Categories")
                        .WithMany("TravelCategory")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelHelperDb.TravelSet", "TravelCategoryCategory")
                        .WithMany("TravelCategory")
                        .HasForeignKey("TravelCategoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelHelperDb.TravelSet", b =>
                {
                    b.HasOne("TravelHelperDb.CitySet", "City")
                        .WithMany("TravelSet")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelHelperDb.UserSet", "User")
                        .WithMany("TravelSet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelHelperDb.UserSet", b =>
                {
                    b.HasOne("TravelHelperDb.UserSettingsSet", "UserSettings")
                        .WithMany("UserSet")
                        .HasForeignKey("UserSettingsId");
                });
#pragma warning restore 612, 618
        }
    }
}
